type: hosts
description: |-
  Host Database

  localhost is used to configure the loopback interface
  when the system is booting.  Do not change this entry.
entries:
  - ip: 127.0.0.1
    hostname: localhost
    description: IPv4 loopback
  - ip: 255.255.255.255.255
    hostname: broadcasthost
    description: Broadcast address for the local network segment
  - ip: ::1
    hostname: localhost
    description: IPv6 loopback
